#!/usr/bin/env bash

(($# < 2)) && echo "Usage: $0 <out-dir> <session-cookie>" && exit 1

mkdir -p "$1" && for i in {1..25}; do
  f=$(printf "%s/day%02d" "$1" "$i")
  u="https://adventofcode.com/2020/day/$i/input"
  [[ -f $f ]] || curl --compressed -#b "session=$2" "$u" > "$f"
done
